DELIMITER ;

DROP TABLE IF EXISTS PRODUCTOIMAGEN;

DELIMITER $$

CREATE TABLE PRODUCTOIMAGEN (
    IDProducto          INT             NOT NULL,
    IDImagen            INT             NOT NULL,

    PRIMARY KEY(IDProducto),
    CONSTRAINT FK_PRODUCTO_IMAGEN FOREIGN KEY(IDProducto) REFERENCES PRODUCTO(IDProducto),
    CONSTRAINT FK_IMAGEN_PRODUCTO FOREIGN KEY(IDImagen) REFERENCES IMAGEN(IDImagen)
)$$
