CREATE TABLE TIPODET (
    IdTipoDet INT NOT NULL AUTO_INCREMENT,
    IdTipo INT NOT NULL,
    Descripcion VARCHAR(50) NOT NULL,
    Valor VARCHAR(50) NOT NULL,

    PRIMARY KEY(IdTipoDet),
    CONSTRAINT FK_TIPODET_TIPO FOREIGN KEY (IdTipo) REFERENCES TIPO (IdTipo)
);
